services:

  db:
    image: postgres:15-alpine
    env_file:
      - .env
  
  web:
    depends_on:
      - db
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./proj:/app
    env_file:
      - .env
    command: >
      sh -c " python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py loaddata /app/fixtures/users.json &&
              python manage.py loaddata /app/fixtures/cars.json &&
              python manage.py loaddata /app/fixtures/comments.json &&
              python manage.py runserver 0.0.0.0:8000"